# Generated by Django 3.0.5 on 2021-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='you can see the beautiful blog page..', max_length=200),
        ),
    ]
