# Generated by Django 3.0.5 on 2021-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_auto_20211004_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
